### ISSUE TITLE
Want the pretrained embeddings of crawl and comm-char

### ISSUE THREAD

**Issue by softhuafei** [Multimodal-NER/RpBERT#2]
Hi, I want to follow this work, can you send me the complete pretrained embeddings of crawl? Thanks!
I tried to download from flair, but it doesn't work.

```
Traceback (most recent call last):
  File "/home/cike/RpBert/main.py", line 132, in <module>
    main()
  File "/home/cike/RpBert/main.py", line 111, in main
    t.train()
  File "/home/cike/RpBert/trainer.py", line 36, in train
    'crawl'),
  File "/home/cike/RpBert/flair/embeddings.py", line 251, in __init__
    f"{base_path}en-fasttext-crawl-300d-1M.vectors.npy", cache_dir=cache_dir
  File "/home/cike/RpBert/flair/file_utils.py", line 88, in cached_path
    return get_from_cache(url_or_filename, dataset_cache)
  File "/home/cike/RpBert/flair/file_utils.py", line 160, in get_from_cache
    response = requests.head(url, headers={"User-Agent": "Flair"})
  File "/home/cike/miniconda3/envs/RpBert/lib/python3.7/site-packages/requests/api.py", line 102, in head
    return request('head', url, **kwargs)
  File "/home/cike/miniconda3/envs/RpBert/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/cike/miniconda3/envs/RpBert/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cike/miniconda3/envs/RpBert/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/cike/miniconda3/envs/RpBert/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /alan-nlp/resources/embeddings-v0.3/en-fasttext-crawl-300d-1M.vectors.npy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1567a3b510>: Failed to establish a new connection: [Errno 110] Connection timed out'))

Process finished with exit code 1

```

**Comment by gagaein** [comment]
I have those pretrained embeddings. If you want it, you can contact me via email.

**Comment by blink7-lab** [comment]
​Hello, I would like the fasttext-crawl word-embedding and comm-char file. Would you like to share it to me? Thank you very much，and look forward to your reply.my mail is goodbail@163.com

**Comment by SuYindu** [comment]
Please refer our new README.
